### ISSUE TITLE
Batch all service annotations together

### ISSUE THREAD

**Issue by prat0318** [Yelp/pyramid_zipkin#23]
Adding an annotation like so:
```
zipkin_logger.debug({'annotations': {'start_db_call': time.time()}})
```
results in warning in Collector console:
```
19:00:58.772 [pool-2-thread-2] WARN  o.t.z.storage.cassandra.Repository - Span 1_547073285_-1325006353 in trace 4848644533043884200 had no timestamp. If this happens a lot consider switching back to SizeTieredCompactionStrategy for zipkin.traces
```

This is because the above debug creates a new span message with no `cs`, `cr` OR `ss`, `sr` pair. These spans can be merged with the service span created [here](https://github.com/Yelp/pyramid_zipkin/blob/master/pyramid_zipkin/logging_helper.py#L90). (by getting all non-client spans from the loop and getting the annotations and binary annotations out).

Also, we should mention in the docs that the client spans SHOULD contain `cs`, `cr` pair.

**Comment by mjbryant** [comment]
@prat0318 so are you saying that annotations logged with no `cs, cr` pairs _should always_ be merged with the service span?

**Comment by prat0318** [comment]
As per maintainers, every span should have a duration. That can be decided if the span has either cs, cr or sr, ss pair.

Some our spans send information of a particular span in pieces. Like:
```
zipkin_logger.debug({'annotations': {'start_db_call': time.time()}})
```
There will be a separate server span with sr, ss timings and then there will be a span with just `start_db_call` annotation. So, the second span is apparently incomplete for which log message is thrown. there is nothing bad about it, its just we can easily batch them up and send it with server span which had sr, ss timings. Collector just throws this warning but proceeds as usual combining the spans together.
