### ISSUE TITLE
Add request.matched_route binary annotation

### ISSUE THREAD

**Issue by mjbryant** [Yelp/pyramid_zipkin#56]
This pyramid construct is often different than the `http.uri` annotation we include by default.

In addition to this it'd be kinda cool to allow users to turn binary annotations added by default on/off. Something like setting a 'default_binary_annotations' list in the pyramid registry. Just an idea.

**Comment by adriancole** [comment]
food for thought.. in other projects we are namespacing library-specific
binary annotations with the name of that library, so it might be
"pyramid.matched_route"
or something..

**Comment by prat0318** [comment]
I like 'pyramid.matched_route'.

Also how about whitelisting array for optional binary annotations and this one would be optional.

**Comment by mjbryant** [comment]
+1. Namespacing all our binary annotations seems like a great idea. We have traces that'll go through both pyramid-zipkin and java-based tracers in the same request.

**Comment by bplotnick** [comment]
This issue will be handled in #89, now that zipkin has a constant defining this.
