### ISSUE TITLE
Report span.timestamp and duration

### ISSUE THREAD

**Issue by adriancole** [Yelp/pyramid_zipkin#68]
While possible to derive a span's timestamp and duration at query time, it is best to report them to zipkin. This reduces the guesswork on the server side, and particularly makes the cassandra storage implementation more effective. This also makes the duration query operable.

### Do we need to do anything?
First, we'd need to report span.timestamp and duration in the first place :) This might start with an upstream change to py_zipkin to capture this. Here's the normal doc on that zipkin.io/pages/instrumenting.html

Then, we'd need to ensure that the special-case of [continuing a client-originated span on the server](https://github.com/openzipkin/openzipkin.github.io/issues/49) is addressed (where B3 headers are read).

Here are tests that should be in place to ensure that span.timestamp and duration are set properly.

* client creates a span and propagates it to a server
  * client propagates b3 headers for trace id, span id, and sampled=1
  * server neither reports span.timestamp nor duration
  * client reports span.timestamp and duration

* server creates a new trace
  * no b3 headers are detected
  * server reports span.timestamp and duration

* server creates a new trace with externally supplied ids
  * caller propagates b3 headers for trace id, span id, but *no sampled header*
  * server reports span.timestamp and duration

Does this make sense? Can anyone here help implement this?

See https://github.com/openzipkin/brave/issues/277#issuecomment-262429392

**Comment by adriancole** [comment]
cc'ing other who use py_zipkin as I think there might be some work done there. plus the same sort of thing applies to anyone reading B3 headers.

@killpanda @GuoJing @xianhuawei

**Comment by GuoJing** [comment]
Got it, but can't find anywhere trace the lib `py_zipkin`.

**Comment by adriancole** [comment]
ex I think here would need span timestamp and duration. ex they should be
conditionally added prior to sending to the transport handler

https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/logging_helper.py#L269

**Comment by mjbryant** [comment]
This sounds doable. I think it'd be entirely in py-zipkin. @adriancole could you create a ticket there? Then this ticket can just become a placeholder ticket.

**Comment by adriancole** [comment]
can do! yeah I think there will be some logic here (since it is parsing the
B3 headers), but you are right much will be upstream, or possibly all if B3
extraction is moved to py-zipkin.

**Comment by adriancole** [comment]
made a mostly same issue here https://github.com/Yelp/py_zipkin/issues/25

**Comment by mjbryant** [comment]
Addressed in https://github.com/Yelp/pyramid_zipkin/pull/72
